apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ext
  namespace: dev
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  type: NodePort
  ports: # TODO: Exclude external services
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30000
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30001